name: Test Release

on: [push]

jobs:
  run_tests:
    name: Testing release variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Local Properties File
        run: touch local.properties

      - name: Add secret API Key
        run: echo "apiKey=\""${{ secrets.FOOTBALL_API_KEY }}"\"" >> local.properties

      - name: Add secret API Key
        run: echo "apiKey=\""${{ secrets.AUTH_WEB_CLIENT_ID }}"\"" >> local.properties

      - name: Add secret API Key
        run: echo "apiKey=\""${{ secrets.NEWS_API_KEY }}"\"" >> local.properties

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - testReleaseUnitTest
        run: ./gradlew testReleaseUnitTest